import type { Metadata } from 'next';
import { pageMeta } from '@/lib/seo/metadata';
import { buildGraph } from '@/lib/schema/graph';
import { JsonLd } from '@/components/JsonLd';
import { Breadcrumbs } from '@/components/site/Breadcrumbs';

export const metadata: Metadata = pageMeta({
  title: 'Investors',
  description:
    'The category thesis: a fragmented, state-licensed trade under active consolidation, with no owned digital community layer. Public thesis, gated numbers.',
  path: '/investors/',
});

/**
 * Funnel 3 of 3: capital. Indexation policy differs from the rest of the site — the thesis is
 * public because it builds inbound interest and category credibility; the numbers are gated
 * because they preserve leverage and keep competitors out. /investors/data-room/ is noindex.
 *
 * SEQUENCING: do not open capital conversations before sponsor revenue is documented.
 * In a trade this small and this well-networked, a premature raise conversation circulates.
 */
export default function InvestorsPage() {
  const crumbs = [
    { name: 'Home', href: '/' },
    { name: 'Investors', href: '/investors/' },
  ];
  const graph = buildGraph({ path: '/investors/', crumbs });

  return (
    <>
      <JsonLd graph={graph} />
      <div className="shell">
        <Breadcrumbs crumbs={crumbs} />
      </div>
      <div className="shell max-w-measure pb-16">
        <p className="eyebrow mb-3">Investors</p>
        <h1 className="display mb-6 max-w-[16ch]">A licensed workforce nobody has ever mapped.</h1>
        <p className="prose-bulletin">
          Structural pest control is a state-licensed trade under active private-equity
          consolidation. Its national association has thousands of members and its largest annual
          gathering draws a few thousand professionals for four days a year. Between those four
          days, the working conversation happens in closed social platforms that no one can
          index, cite, measure or monetise.
        </p>
        <p className="prose-bulletin">
          What is being built here is not a media property with a community bolted on. It is a
          licence-verified professional identity graph, an owned distribution channel into a
          workforce that manufacturers currently reach only through distributors, proprietary
          competency data generated by competition, and a compounding evergreen reference corpus
          in a category where no incumbent has built one.
        </p>

        <ul className="mono mt-10 space-y-2 text-ink2">
          <li><a className="hover:text-ink" href="/investors/thesis/">The thesis in full</a></li>
          <li><a className="hover:text-ink" href="/investors/traction/">Traction</a></li>
          <li><a className="hover:text-ink" href="/investors/team/">Team</a></li>
        </ul>
      </div>
    </>
  );
}
